import { Geist, Geist_Mono } from "next/font/google";
import Header from '@/components/Header';
import "./globals.css";
import ReduxProvider from '@/store/ReduxProvider';
import SessionProvider from "./Provider/sessionprovider";
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <SessionProvider>
        <ReduxProvider>
        <Header />
        {children}
        <ToastContainer 
          style={{ width: '100%', maxWidth: '400px', margin: '0 auto', marginTop:'70 px' }}
          autoClose={1500}
          theme= "dark" />
        </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
